version: '3.9'
services:
  main:
    container_name: Serve
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    ports:
      - 8000:8000
    networks:
      - laravel-exa

  db:
    image: mysql:8.0
    container_name: db
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3301:3306
    networks:
      - laravel-exa
      
volumes:
  db:
    driver: local

networks:
  laravel-exa:
    driver: bridge